## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3281, 0.9758, 0.0041, 0.4364],
        [0.8859, 0.0735, 0.6670, 0.4522],
        [0.3818, 0.5331, 0.8711, 0.1813]])

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [22]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes 

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4978, 0.7387, 0.8409, 0.9941],
        [0.5377, 0.8294, 0.9277, 0.0379],
        [0.2737, 0.9886, 0.5602, 0.2838]])

In [31]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4978, 0.7387, 0.8409, 0.9941],
        [0.5377, 0.8294, 0.9277, 0.0379],
        [0.2737, 0.9886, 0.5602, 0.2838]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor opertions include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [36]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mutliplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [38]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [41]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.12 ms, sys: 1.02 ms, total: 2.14 ms
Wall time: 1.95 ms


In [42]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 138 µs, sys: 27 µs, total: 165 µs
Wall time: 148 µs


tensor(14)

* Pytorch methods much faster than your scratch functions so if there a method in Pytorch use it!

### One of the most common errors in deep learning: shape mismatch

In [43]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's just an alias)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [44]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [45]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [46]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [47]:
# the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: Tensor_A: {tensor_A.shape}, Tensor_B: {tensor_B.shape}")
print(f"New shapes: Tensor_A: {tensor_A.shape},Tensor_B: {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimensions must match!")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: Tensor_A: torch.Size([3, 2]), Tensor_B: torch.Size([3, 2])
New shapes: Tensor_A: torch.Size([3, 2]),Tensor_B: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimensions must match!
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [48]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [49]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [50]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [51]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [52]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [53]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
# Find the position in tensor that has the minimum value with argmin().
# argmin() -> returns the index position of target tensor where the minimum value is occurs.
x.argmin()

tensor(0)

In [55]:
x[0]

tensor(1)

In [56]:
# Find the position in tensor that has the maximum value with argmax().
# argmax() -> returns the index position of target tensor where the maximum value is occurs.
x.argmax()

tensor(9)

In [57]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [58]:
 # Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous tensor shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x_reshaped)
print(f"\nnew tensor: {x_squeezed}")
print(f"new tensor shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous tensor shape: torch.Size([1, 9])

new tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new tensor shape: torch.Size([9])


In [73]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specified dim (dimension)
print(f"previous target: {x_squeezed}")
print(f"previous target shape: {x_squeezed.shape}")

# Add a dimension to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nnew tensor: {x_unsqueezed}")
print(f"new tensor shape: {x_unsqueezed.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous target shape: torch.Size([9])

new tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new tensor shape: torch.Size([1, 9])


In [75]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0 

print(f"Previous shape: {x_original.shape}") # [height, width, colour_channels]
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with Numpy

In [76]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
# Let's index on the middle bracket (dim=1)
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [80]:
# Let's index on the inner bracket (last dim)
x[0, 0, 0], x[0][0][0]

(tensor(1), tensor(1))

In [82]:
# Let's get number 9
x[0][2][2]

tensor(9)

In [83]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [85]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [87]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [88]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## Pytorch tensors & Numpy

NumPy is a populer scientific Python numerical computing library.

And because of this, Pytorch has functionally to interact with it.

* Data in NumPy, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [93]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [95]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [96]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [97]:
# Change the tensor, what will this do to the numpy array?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again ...`

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [101]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(size=(3, 4))
random_tensor_B = torch.rand(size=(3, 4))

print(f"Random tensor A:\n {random_tensor_A}")
print(f"Random tensor B:\n {random_tensor_B}")
print(random_tensor_A == random_tensor_B)

Random tensor A:
 tensor([[0.6259, 0.8167, 0.8776, 0.5642],
        [0.2693, 0.0833, 0.6767, 0.3970],
        [0.9519, 0.0792, 0.4269, 0.4309]])
Random tensor B:
 tensor([[0.7482, 0.0584, 0.6340, 0.5304],
        [0.4849, 0.1700, 0.6455, 0.0712],
        [0.0585, 0.7667, 0.7223, 0.1955]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(size=(3, 4))

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(size=(3, 4))

print(f"Random tensor C:\n {random_tensor_C}")
print(f"Random tensor D:\n {random_tensor_D}")
print(random_tensor_C == random_tensor_D)

Random tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random tensor D:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html

## Check for GPU access with Pytorch

In [1]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g run on GPU if available, else default to CPU.

In [6]:
# Setup device agnostic code - mps is for Apple Silicon
device = "mps" if getattr(torch,'has_mps',False) \
    else "gpu" if torch.cuda.is_available() else "cpu"
device

'mps'

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.


In [8]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(f"Is tensor on GPU: {tensor, tensor.device}")

# Move tensor to GPU
tensor = tensor.to(device)

# Tensor on GPU
print(f"Is tensor on GPU: {tensor}")

# Move tensor to CPU
tensor = tensor.to("cpu")
print(f"Is tensor on GPU: {tensor, tensor.device}")

Is tensor on GPU: (tensor([1, 2, 3]), device(type='cpu'))
Is tensor on GPU: tensor([1, 2, 3], device='mps:0')
Is tensor on GPU: (tensor([1, 2, 3]), device(type='cpu'))
